name: "Run docker build and push"

on:
    push:
        branches:
            - main
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            # - name: Docker Build
            #   run: |
            #       make build

            - name: Docker login
              run: |
                  make docker-login

            - name: Docker Push
              run: |
                   make push