name: "Run docker build and push"

on:
    push:
        branches:
            - main
            - master

jobs:
    agw-build-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2


            - name: Docker login
              run: |
                  make docker-login

            - name: Docker API Push
              run: |
                   make api-push

           
    todo-build-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

           
            - name: Docker login
              run: |
                  make docker-login

           

            - name: Docker TODO Push
              run: |
                    make todo-push